In [1]:
# Import necessary libraries.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('./data/WA_Fn-UseC_-Telco-Customer-Churn_R2.csv')

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,1,0,1,0,0,1,0,...,0,0,0,0,0,1,2,29.85,29.85,0
1,5575-GNVDE,1,0,0,0,34,1,0,1,1,...,1,0,0,0,1,0,3,56.95,1889.50,0
2,3668-QPYBK,1,0,0,0,2,1,0,1,1,...,0,0,0,0,0,1,3,53.85,108.15,1
3,7795-CFOCW,1,0,0,0,45,0,0,1,1,...,1,1,0,0,1,0,0,42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,0,2,0,...,0,0,0,0,0,1,2,70.70,151.65,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7011 entries, 0 to 7010
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7011 non-null   object
 1   gender            7011 non-null   int64
 2   SeniorCitizen     7011 non-null   int64
 3   Partner           7011 non-null   int64
 4   Dependents        7011 non-null   int64
 5   Tenure            7011 non-null   int64
 6   PhoneService      7011 non-null   int64
 7   MultipleLines     7011 non-null   int64
 8   InternetService   7011 non-null   int64
 9   OnlineSecurity    7011 non-null   int64
 10  OnlineBackup      7011 non-null   int64
 11  DeviceProtection  7011 non-null   int64
 12  TechSupport       7011 non-null   int64
 13  StreamingTV       7011 non-null   int64
 14  StreamingMovies   7011 non-null   int64
 15  Contract          7011 non-null   int64
 16  PaperlessBilling  7011 non-null   int64
 17  PaymentMethod     7011 non-null   int64
 18  MonthlyCharges    7011 non-null   float64
 19  TotalCharges      7011 non-null   float64
 20  Churn             7011 non-null   int64
dtypes: float64(2), int64(18), object(1)
memory usage: 1.1+ MB